# Generated by Django 5.1.6 on 2025-02-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='age',
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(default='Not Available', max_length=50),
        ),
    ]
