# Generated by Django 5.1.6 on 2025-02-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_doctor_doctor_id_alter_doctor_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_id',
            field=models.PositiveIntegerField(editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
