# Generated by Django 5.1.6 on 2025-02-27 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_patient_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
    ]
