# Generated by Django 5.1.6 on 2025-04-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='feedback',
            name='additional_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='facility_quality',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feedback',
            name='staff_behavior',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feedback',
            name='treatment_quality',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feedback',
            name='wait_time',
            field=models.IntegerField(default=0),
        ),
    ]
