# Generated by Django 5.1.6 on 2025-05-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_rename_submitted_at_feedback_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='issue',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
