# Generated by Django 5.1.6 on 2025-05-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_patient_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='room_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
