# Generated by Django 5.1.6 on 2025-05-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_patient_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='room_type',
            field=models.CharField(choices=[('General Ward', 'General Ward'), ('Emergency', 'Emergency'), ('Super Speciality', 'Super Speciality'), ('Luxury', 'Luxury')], default='General Ward', max_length=50),
        ),
    ]
