# Generated by Django 5.1.6 on 2025-05-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_patient_room_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(max_length=10)),
                ('occupation', models.CharField(default='Nurse', max_length=50)),
                ('shift', models.CharField(max_length=100)),
                ('availability', models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy')], default='Available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(max_length=10)),
                ('occupation', models.CharField(max_length=100)),
                ('shift', models.CharField(max_length=50)),
                ('availability', models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy')], max_length=20)),
            ],
        ),
    ]
