# Generated by Django 5.1.6 on 2025-05-03 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_alter_doctor_mobile_alter_nurse_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse',
            name='occupation',
        ),
    ]
