# Generated by Django 5.1.6 on 2025-05-03 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0016_remove_nurse_occupation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_charge', models.DecimalField(decimal_places=2, default=2000.0, max_digits=10)),
                ('scan_charge', models.DecimalField(decimal_places=2, default=1500.0, max_digits=10)),
                ('medicine_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gst', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
        ),
    ]
